#ifndef QCONTACTCHOOSERDIALOG_GLOBAL_H
#define QCONTACTCHOOSERDIALOG_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QCONTACTCHOOSERDIALOG_LIBRARY)
#  define QCONTACTCHOOSERDIALOGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QCONTACTCHOOSERDIALOGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QCONTACTCHOOSERDIALOG_GLOBAL_H
